# ---------- Build Stage ----------
FROM node:22 AS build

WORKDIR /app

# Copy dependency files from repo root
COPY package*.json ./

RUN npm install

# Copy only the shell project into the container
COPY projects/shell ./projects/shell
COPY angular.json ./
COPY tsconfig*.json ./

# Build the shell host
RUN npx ng build shell --configuration=production

# ---------- Runtime Stage ----------
FROM nginx:alpine

# Copy nginx configuration profile from docker folder
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built Angular shell app into nginx html directory
COPY --from=build /app/dist/shell/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
